/** Friendly room code format generated by the backend (e.g. ABC-1234). */
export const ROOM_ID_PATTERN = /^[A-Za-z]{3}-\d{4}$/;

export function isValidRoomIdFormat(roomId: string): boolean {
	return ROOM_ID_PATTERN.test(roomId.trim());
}

/** Normalizes user input to the backend's uppercase code format. */
export function normalizeRoomId(roomId: string): string {
	const trimmed = roomId.trim();
	const match = trimmed.match(/^([A-Za-z]{3})-(\d{4})$/);
	if (!match) return trimmed;
	return `${match[1].toUpperCase()}-${match[2]}`;
}
